language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

before_install:
  - gem update --system
  - gem update bundler

install:
    - 'bundle install'

gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0gemfile
