language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - 2.0.0
before_install:
  - gem update --system
  - gem update bundler
before_script:
  - 'bundle install'
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0gemfile
